from __future__ import annotations

from dataclasses import asdict, dataclass, field
import json
from pathlib import Path
import subprocess
from typing import Any

from wm.config import Settings
from wm.db.mysql_cli import MysqlCliClient, MysqlCliError
from wm.spells.shell_bank import SpellShellDefinition
from wm.spells.shell_bank import load_spell_shell_bank

REQUIRED_TABLES = {"wm_spell_shell", "wm_spell_behavior"}
OPTIONAL_TABLES = {"wm_spell_grant", "wm_spell_debug_request", "wm_publish_log", "wm_rollback_snapshot"}


@dataclass(slots=True)
class WmSpellShellDraft:
    shell_key: str
    spell_id: int
    family_id: str
    label: str
    behavior_kind: str
    targeting: str
    required_level: int
    client_patch_version: str
    shell_state: str = "draft"
    behavior_state: str = "active"
    tooltip: str | None = None
    icon_hint: str | None = None
    ownership_key: str | None = None
    provenance: dict[str, Any] = field(default_factory=dict)
    behavior_config: dict[str, Any] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class SpellPlatformIssue:
    path: str
    message: str
    severity: str = "error"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class SpellPlatformPreflight:
    spell_id: int
    issues: list[SpellPlatformIssue] = field(default_factory=list)
    detected_tables: dict[str, bool] = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return not any(issue.severity == "error" for issue in self.issues)

    def to_dict(self) -> dict[str, Any]:
        return {
            "spell_id": self.spell_id,
            "ok": self.ok,
            "issues": [issue.to_dict() for issue in self.issues],
            "detected_tables": self.detected_tables,
        }


@dataclass(slots=True)
class SpellPlatformSqlPlan:
    spell_id: int
    statements: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class SpellPlatformPublishResult:
    mode: str
    draft: dict[str, Any]
    validation: dict[str, Any]
    preflight: dict[str, Any]
    sql_plan: dict[str, Any]
    applied: bool

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class SpellBehaviorDebugRequest:
    request_id: int
    player_guid: int
    behavior_kind: str
    payload: dict[str, Any]
    status: str
    result: dict[str, Any] = field(default_factory=dict)
    error_text: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def default_shell_draft_path(*, shell_key: str) -> Path:
    return Path(__file__).resolve().parents[3].joinpath(".wm-bootstrap", "state", "content-drafts", f"shell-{shell_key}.json")


def create_shell_draft(
    *,
    shell_key: str,
    ownership_key: str | None = None,
    player_guid: int | None = None,
    behavior_config: dict[str, Any] | None = None,
    shell_bank_path: str | Path | None = None,
) -> WmSpellShellDraft:
    bank = load_spell_shell_bank(shell_bank_path)
    shell = bank.shell_by_key(shell_key)
    if shell is None:
        raise ValueError(f"Unknown shell key: {shell_key}")
    patch_version = bank.patch.get("artifact_version", "wm_spell_shell_bank.v1")
    return WmSpellShellDraft(
        shell_key=shell.shell_key,
        spell_id=shell.spell_id,
        family_id=shell.family_id,
        label=shell.label,
        behavior_kind=shell.behavior_kind,
        targeting=shell.targeting,
        required_level=shell.required_level,
        client_patch_version=patch_version,
        tooltip=shell.tooltip,
        icon_hint=shell.icon_hint,
        ownership_key=ownership_key or f"wm.spell_shell:{shell.shell_key}",
        provenance={
            "player_guid": player_guid,
            "shell_bank_path": str(shell_bank_path or Path("control/runtime/spell_shell_bank.json")),
        },
        behavior_config=_default_behavior_config(shell) | dict(behavior_config or {}),
        notes=list(shell.notes),
    )


def write_shell_draft_file(*, draft: WmSpellShellDraft, out_path: Path | None = None) -> Path:
    output = out_path or default_shell_draft_path(shell_key=draft.shell_key)
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "kind": "wm_spell_shell",
        "template": "wm_spell_shell",
        "draft": draft.to_dict(),
        "notes": [
            "Generated by wm.spells.platform.",
            "Publish with python -m wm.content.workbench publish-shell --draft-json <path>.",
        ],
    }
    output.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return output


def load_shell_draft(path: str | Path) -> WmSpellShellDraft:
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    if isinstance(raw, dict) and isinstance(raw.get("draft"), dict):
        raw = raw["draft"]
    if not isinstance(raw, dict):
        raise ValueError("WM spell shell draft JSON must be an object.")
    return WmSpellShellDraft(
        shell_key=str(raw["shell_key"]),
        spell_id=int(raw["spell_id"]),
        family_id=str(raw["family_id"]),
        label=str(raw["label"]),
        behavior_kind=str(raw["behavior_kind"]),
        targeting=str(raw["targeting"]),
        required_level=int(raw.get("required_level") or 1),
        client_patch_version=str(raw.get("client_patch_version") or "wm_spell_shell_bank.v1"),
        shell_state=str(raw.get("shell_state") or "draft"),
        behavior_state=str(raw.get("behavior_state") or "active"),
        tooltip=(str(raw["tooltip"]) if raw.get("tooltip") not in (None, "") else None),
        icon_hint=(str(raw["icon_hint"]) if raw.get("icon_hint") not in (None, "") else None),
        ownership_key=(str(raw["ownership_key"]) if raw.get("ownership_key") not in (None, "") else None),
        provenance=dict(raw.get("provenance") or {}),
        behavior_config=dict(raw.get("behavior_config") or {}),
        notes=[str(note) for note in raw.get("notes", [])],
    )


class SpellPlatformPublisher:
    def __init__(self, *, client: MysqlCliClient, settings: Settings) -> None:
        self.client = client
        self.settings = settings

    def validate(self, draft: WmSpellShellDraft) -> dict[str, Any]:
        issues: list[SpellPlatformIssue] = []
        if draft.family_id not in {family.family_id for family in load_spell_shell_bank().families}:
            issues.append(SpellPlatformIssue(path="family_id", message=f"Unknown shell family: {draft.family_id}"))
        if not draft.behavior_kind.strip():
            issues.append(SpellPlatformIssue(path="behavior_kind", message="behavior_kind is required"))
        if draft.spell_id <= 0:
            issues.append(SpellPlatformIssue(path="spell_id", message="spell_id must be positive"))
        return {
            "ok": not any(issue.severity == "error" for issue in issues),
            "issues": [issue.to_dict() for issue in issues],
        }

    def preflight(self, draft: WmSpellShellDraft) -> SpellPlatformPreflight:
        report = SpellPlatformPreflight(spell_id=draft.spell_id)
        report.detected_tables = self._table_presence(REQUIRED_TABLES | OPTIONAL_TABLES)
        for table_name in sorted(REQUIRED_TABLES):
            if not report.detected_tables.get(table_name, False):
                report.issues.append(
                    SpellPlatformIssue(path=f"table.{table_name}", message=f"Required table `{table_name}` is missing.")
                )
        return report

    def build_sql_plan(self, draft: WmSpellShellDraft) -> SpellPlatformSqlPlan:
        provenance_json = json.dumps(draft.provenance, ensure_ascii=False)
        behavior_json = json.dumps(draft.behavior_config, ensure_ascii=False)
        statements = [
            (
                "INSERT INTO wm_spell_shell "
                "(ShellSpellID, ShellKey, FamilyID, Label, State, ClientPatchVersion, OwnershipKey, ProvenanceJSON) VALUES "
                f"({int(draft.spell_id)}, {_sql_string(draft.shell_key)}, {_sql_string(draft.family_id)}, {_sql_string(draft.label)}, "
                f"{_sql_string(draft.shell_state)}, {_sql_string(draft.client_patch_version)}, {_sql_string_or_null(draft.ownership_key)}, {_sql_string(provenance_json)}) "
                "ON DUPLICATE KEY UPDATE "
                "ShellKey = VALUES(ShellKey), FamilyID = VALUES(FamilyID), Label = VALUES(Label), State = VALUES(State), "
                "ClientPatchVersion = VALUES(ClientPatchVersion), OwnershipKey = VALUES(OwnershipKey), ProvenanceJSON = VALUES(ProvenanceJSON), UpdatedAt = CURRENT_TIMESTAMP;"
            ),
            (
                "INSERT INTO wm_spell_behavior "
                "(ShellSpellID, BehaviorKind, ConfigJSON, Status) VALUES "
                f"({int(draft.spell_id)}, {_sql_string(draft.behavior_kind)}, {_sql_string(behavior_json)}, {_sql_string(draft.behavior_state)}) "
                "ON DUPLICATE KEY UPDATE "
                "BehaviorKind = VALUES(BehaviorKind), ConfigJSON = VALUES(ConfigJSON), Status = VALUES(Status), UpdatedAt = CURRENT_TIMESTAMP;"
            ),
        ]
        return SpellPlatformSqlPlan(spell_id=draft.spell_id, statements=statements)

    def publish(self, *, draft: WmSpellShellDraft, mode: str) -> SpellPlatformPublishResult:
        validation = self.validate(draft)
        preflight = self.preflight(draft)
        sql_plan = self.build_sql_plan(draft) if validation["ok"] and preflight.ok else SpellPlatformSqlPlan(spell_id=draft.spell_id)

        if mode not in {"dry-run", "apply"}:
            raise ValueError(f"Unsupported publish mode: {mode}")

        if mode == "dry-run" or not validation["ok"] or not preflight.ok:
            return SpellPlatformPublishResult(
                mode=mode,
                draft=draft.to_dict(),
                validation=validation,
                preflight=preflight.to_dict(),
                sql_plan=sql_plan.to_dict(),
                applied=False,
            )

        try:
            if preflight.detected_tables.get("wm_publish_log", False):
                self._execute_world(
                    "INSERT INTO wm_publish_log (artifact_type, artifact_entry, action, status, notes) VALUES "
                    f"('spell_shell', {int(draft.spell_id)}, 'publish', 'started', 'WM spell shell publish started')"
                )
            for statement in sql_plan.statements:
                self._execute_world(statement)
            if preflight.detected_tables.get("wm_publish_log", False):
                self._execute_world(
                    "INSERT INTO wm_publish_log (artifact_type, artifact_entry, action, status, notes) VALUES "
                    f"('spell_shell', {int(draft.spell_id)}, 'publish', 'success', 'WM spell shell publish completed')"
                )
        except MysqlCliError as exc:
            raise MysqlCliError(f"WM spell shell publish failed for {draft.spell_id}: {exc}") from exc

        return SpellPlatformPublishResult(
            mode=mode,
            draft=draft.to_dict(),
            validation=validation,
            preflight=preflight.to_dict(),
            sql_plan=sql_plan.to_dict(),
            applied=True,
        )

    def _table_presence(self, table_names: set[str]) -> dict[str, bool]:
        rows = self.client.query(
            host=self.settings.world_db_host,
            port=self.settings.world_db_port,
            user=self.settings.world_db_user,
            password=self.settings.world_db_password,
            database="information_schema",
            sql=(
                "SELECT TABLE_NAME FROM information_schema.TABLES "
                f"WHERE TABLE_SCHEMA = {_sql_string(self.settings.world_db_name)} "
                f"AND TABLE_NAME IN ({_sql_list(table_names)})"
            ),
        )
        present = {str(row['TABLE_NAME']): True for row in rows}
        return {name: present.get(name, False) for name in table_names}

    def _execute_world(self, sql: str) -> None:
        command = [
            str(self.client.mysql_bin_path),
            f"--host={self.settings.world_db_host}",
            f"--port={self.settings.world_db_port}",
            f"--user={self.settings.world_db_user}",
            f"--password={self.settings.world_db_password}",
            f"--database={self.settings.world_db_name}",
            f"--execute={sql}",
        ]
        completed = subprocess.run(
            command,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
        )
        if completed.returncode != 0:
            raise MysqlCliError(completed.stderr.strip() or completed.stdout.strip() or "mysql execute failed")


class SpellBehaviorDebugClient:
    def __init__(self, *, client: MysqlCliClient, settings: Settings) -> None:
        self.client = client
        self.settings = settings

    def submit(
        self,
        *,
        player_guid: int,
        behavior_kind: str,
        payload: dict[str, Any] | None = None,
    ) -> SpellBehaviorDebugRequest:
        request_id = self.submit_fast(player_guid=player_guid, behavior_kind=behavior_kind, payload=payload)
        request = self.get(request_id=request_id)
        if request is None:
            raise RuntimeError(f"WM spell debug request {request_id} was created but could not be loaded.")
        return request

    def submit_fast(
        self,
        *,
        player_guid: int,
        behavior_kind: str,
        payload: dict[str, Any] | None = None,
    ) -> int:
        payload_json = json.dumps(payload or {}, ensure_ascii=False, sort_keys=True)
        rows = self._query_world(
            "INSERT INTO wm_spell_debug_request (PlayerGUID, BehaviorKind, PayloadJSON, Status) VALUES ("
            f"{int(player_guid)}, {_sql_string(behavior_kind)}, {_sql_string(payload_json)}, 'pending'"
            "); SELECT LAST_INSERT_ID() AS RequestID"
        )
        request_id = int(rows[0]["RequestID"]) if rows else 0
        if request_id <= 0:
            raise RuntimeError("WM spell debug request was not created.")
        return request_id

    def get(self, *, request_id: int) -> SpellBehaviorDebugRequest | None:
        rows = self._query_world(
            "SELECT RequestID, PlayerGUID, BehaviorKind, PayloadJSON, Status, ResultJSON, ErrorText "
            "FROM wm_spell_debug_request "
            f"WHERE RequestID = {int(request_id)} LIMIT 1"
        )
        if not rows:
            return None
        row = rows[0]
        return SpellBehaviorDebugRequest(
            request_id=int(row["RequestID"]),
            player_guid=int(row["PlayerGUID"]),
            behavior_kind=str(row["BehaviorKind"]),
            payload=_parse_json(row.get("PayloadJSON")),
            status=str(row["Status"]),
            result=_parse_json(row.get("ResultJSON")),
            error_text=(str(row["ErrorText"]) if row.get("ErrorText") not in (None, "") else None),
        )

    def _query_world(self, sql: str) -> list[dict[str, Any]]:
        return self.client.query(
            host=self.settings.world_db_host,
            port=self.settings.world_db_port,
            user=self.settings.world_db_user,
            password=self.settings.world_db_password,
            database=self.settings.world_db_name,
            sql=sql,
        )


def _default_behavior_config(shell: SpellShellDefinition) -> dict[str, Any]:
    if shell.behavior_kind == "summon_bonebound_servant_v1":
        return {
            "creature_entry": 1860,
            "display_id": 734,
            "name": "Bonebound Servant",
            "require_corpse": True,
            "persist_pet": True,
            "owner_intellect_to_all_stats": True,
            "owner_shadow_power_to_attack_power": True,
            "virtual_item_1": 1897,
            "virtual_item_2": 0,
            "virtual_item_3": 0,
            "base_health": 140,
            "health_per_level": 24,
            "health_per_intellect": 5,
            "health_per_shadow_power": 2,
            "base_min_damage": 7,
            "base_max_damage": 11,
            "damage_per_level_pct": 125,
            "damage_per_intellect_pct": 8,
            "damage_per_shadow_power_pct": 16,
            "scale_base": 1.0,
            "scale_per_level": 0.005,
            "scale_per_intellect": 0.001,
            "scale_per_shadow_power": 0.0007,
            "attack_time_ms": 2000,
        }
    if shell.behavior_kind == "summon_bonebound_twin_v2":
        return {
            "creature_entry": 1860,
            "display_id": 734,
            "name": "Bonebound Alpha",
            "require_corpse": False,
            "persist_pet": True,
            "spawn_omega": True,
            "preserve_base_stats": True,
            "owner_intellect_to_all_stats": True,
            "owner_intellect_to_all_stats_scale": 1.0,
            "owner_shadow_power_to_attack_power": True,
            "owner_shadow_power_to_attack_power_scale": 1.0,
            "virtual_item_1": 28773,
            "virtual_item_2": 0,
            "virtual_item_3": 0,
            "omega_creature_entry": 1860,
            "omega_name": "Bonebound Omega",
            "omega_display_id": 734,
            "omega_virtual_item_1": 28773,
            "omega_virtual_item_2": 0,
            "omega_virtual_item_3": 0,
            "omega_scale_multiplier": 1.0,
            "omega_health_pct": 100,
            "omega_damage_pct": 100,
            "omega_follow_distance": 2.2,
            "omega_follow_angle": -1.5708,
        }
    if shell.behavior_kind == "passive_intellect_block_v1":
        return {
            "intellect_to_block_rating_scale": 1.0,
            "spell_power_to_block_rating_scale": 1.0,
            "spell_school_mask": 126,
            "max_block_rating": 0,
        }
    return {}


def _sql_string(value: str) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def _sql_string_or_null(value: str | None) -> str:
    if value in (None, ""):
        return "NULL"
    return _sql_string(value)


def _sql_list(values: set[str]) -> str:
    return ", ".join(_sql_string(value) for value in sorted(values))


def _parse_json(value: Any) -> dict[str, Any]:
    if value in (None, ""):
        return {}
    try:
        parsed = json.loads(str(value))
    except json.JSONDecodeError:
        return {"raw": str(value)}
    return parsed if isinstance(parsed, dict) else {"value": parsed}
