param(
    [string]$WorkspaceRoot = "D:\WOW\Azerothcore_WoTLK_Rebuild",
    [string]$SourceRoot
)

$ErrorActionPreference = "Stop"

function Replace-InFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$OldValue,
        [Parameter(Mandatory = $true)]
        [string]$NewValue
    )

    if (-not (Test-Path $Path)) {
        throw "Overlay target not found: $Path"
    }

    $content = Get-Content -Path $Path -Raw
    if ($content.Contains($NewValue)) {
        return
    }
    if (-not $content.Contains($OldValue)) {
        throw "Expected text was not found in $Path"
    }

    $updated = $content.Replace($OldValue, $NewValue)
    Set-Content -Path $Path -Value $updated
}

function Get-ExpectedLoaderSymbol {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ModuleName
    )

    return "Add$($ModuleName.Replace('-', '_'))Scripts"
}

function Get-DefinedLoaderSymbols {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ModuleSourcePath
    )

    if (-not (Test-Path $ModuleSourcePath)) {
        return @()
    }

    $pattern = '^\s*void\s+(Add[A-Za-z0-9_]+Scripts)\s*\(\s*\)\s*(?:\r?\n\s*)?\{'
    $symbols = New-Object System.Collections.Generic.List[string]
    foreach ($file in Get-ChildItem -Path $ModuleSourcePath -Recurse -Filter '*.cpp' -ErrorAction SilentlyContinue) {
        if ($file.Name -ieq 'wm_loader_compat.cpp') {
            continue
        }
        $content = Get-Content -Path $file.FullName -Raw
        foreach ($match in [regex]::Matches($content, $pattern, [System.Text.RegularExpressions.RegexOptions]::Multiline)) {
            $symbols.Add($match.Groups[1].Value)
        }
    }
    return @($symbols | Sort-Object -Unique)
}

function Sync-LoaderCompatibilityWrapper {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ModuleRoot,
        [hashtable]$LoaderSymbolOverrides
    )

    $moduleName = Split-Path -Leaf $ModuleRoot
    $moduleSourcePath = Join-Path $ModuleRoot 'src'
    $wrapperPath = Join-Path $moduleSourcePath 'wm_loader_compat.cpp'
    $expectedSymbol = Get-ExpectedLoaderSymbol -ModuleName $moduleName
    $definedSymbols = @(Get-DefinedLoaderSymbols -ModuleSourcePath $moduleSourcePath)

    if ($definedSymbols -ccontains $expectedSymbol) {
        if (Test-Path $wrapperPath) {
            Remove-Item -LiteralPath $wrapperPath -Force
        }
        return $null
    }

    $actualSymbol = $null
    if ($LoaderSymbolOverrides -and $LoaderSymbolOverrides.ContainsKey($moduleName)) {
        $overrideSymbol = $LoaderSymbolOverrides[$moduleName]
        if ($definedSymbols -ccontains $overrideSymbol) {
            $actualSymbol = $overrideSymbol
        }
        else {
            if (Test-Path $wrapperPath) {
                Remove-Item -LiteralPath $wrapperPath -Force
            }
            return [pscustomobject]@{
                module = $moduleName
                expected = $expectedSymbol
                actual = ($definedSymbols -join ',')
            }
        }
    }

    if (-not $actualSymbol -and $definedSymbols.Count -eq 1) {
        $actualSymbol = $definedSymbols[0]
    }

    if (-not $actualSymbol) {
        if (Test-Path $wrapperPath) {
            Remove-Item -LiteralPath $wrapperPath -Force
        }
        return [pscustomobject]@{
            module = $moduleName
            expected = $expectedSymbol
            actual = ($definedSymbols -join ',')
        }
    }

    $wrapperContent = @(
        "// Auto-generated by Apply-RepackCompatibilityOverlay.ps1",
        "// Keeps legacy/community module loader names compatible with the current CMake-generated ModulesLoader.cpp.",
        "",
        "void $actualSymbol();",
        "",
        "void $expectedSymbol()",
        "{",
        "    $actualSymbol();",
        "}",
        ""
    )
    Set-Content -Path $wrapperPath -Value $wrapperContent
    return $null
}

if (-not $SourceRoot) {
    $portableRoot = Join-Path $WorkspaceRoot "src\azerothcore"
    $legacyRoot = Join-Path $WorkspaceRoot "source\azerothcore"
    if (Test-Path $portableRoot) {
        $SourceRoot = $portableRoot
    }
    else {
        $SourceRoot = $legacyRoot
    }
}

$sourceRoot = $SourceRoot

$bgQueueCheckerPath = Join-Path $sourceRoot "modules\bgqueuechecker\src\BGQueueChecker.cpp"
Replace-InFile `
    -Path $bgQueueCheckerPath `
    -OldValue "    bool CanJoinInBattlegroundQueue(Player* player, ObjectGuid /*BattlemasterGuid*/, BattlegroundTypeId /*BGTypeID*/, uint8 joinAsGroup, GroupJoinBattlegroundResult& err) override" `
    -NewValue "    bool OnPlayerCanJoinInBattlegroundQueue(Player* player, ObjectGuid /*BattlemasterGuid*/, BattlegroundTypeId /*BGTypeID*/, uint8 joinAsGroup, GroupJoinBattlegroundResult& err) override"

$spawnratesHeaderPath = Join-Path $sourceRoot "modules\mod-changeablespawnrates\src\ChangeableSpawnrates.h"
Replace-InFile `
    -Path $spawnratesHeaderPath `
    -OldValue "    void OnLogin(Player* APlayer) override;`r`n    void OnLogout(Player* APlayer) override;" `
    -NewValue "    void OnPlayerLogin(Player* APlayer) override;`r`n    void OnPlayerLogout(Player* APlayer) override;"

$spawnratesCppPath = Join-Path $sourceRoot "modules\mod-changeablespawnrates\src\ChangeableSpawnrates.cpp"
Replace-InFile `
    -Path $spawnratesCppPath `
    -OldValue "#include ""ChangeableSpawnrates.h""" `
    -NewValue "#include ""ChangeableSpawnrates.h""`r`n#include ""WorldSessionMgr.h"""
Replace-InFile `
    -Path $spawnratesCppPath `
    -OldValue "        uint32 xCountOnlinePlayers = sWorld->GetPlayerCount();" `
    -NewValue "        uint32 xCountOnlinePlayers = sWorldSessionMgr->GetPlayerCount();"
Replace-InFile `
    -Path $spawnratesCppPath `
    -OldValue "void CSRPlayer::OnLogin(Player* APlayer)" `
    -NewValue "void CSRPlayer::OnPlayerLogin(Player* APlayer)"
Replace-InFile `
    -Path $spawnratesCppPath `
    -OldValue "void CSRPlayer::OnLogout(Player* APlayer)" `
    -NewValue "void CSRPlayer::OnPlayerLogout(Player* APlayer)"

$deadMeansDeadPath = Join-Path $sourceRoot "modules\mod-dead-means-dead\src\DeadMeansDead.cpp"
Replace-InFile `
    -Path $deadMeansDeadPath `
    -OldValue "    void OnLogin(Player* player) override" `
    -NewValue "    void OnPlayerLogin(Player* player) override"

$loaderSymbolOverrides = @{
    "1v1arena" = "Addmod_1v1_arenaScripts"
    "autobalance" = "Addmod_autobalanceScripts"
    "autorevive" = "Addmod_auto_reviveScripts"
    "bgqueuechecker" = "AddBGQueueCheckerScripts"
    "breakingnews" = "Addmod_breaking_news_overrideScripts"
    "cfbg" = "Addmod_cfbgScripts"
    "challenge-modes" = "Addmod_challenge_modesScripts"
    "desertion-warnings" = "Addmod_desertion_warningsScripts"
    "duelreset" = "Addmod_duel_resetScripts"
    "dynamicxp" = "Addmod_dynamic_xpScripts"
    "emblem-transfer" = "Addmod_emblem_transferScripts"
    "individual-xp" = "Addmod_individual_xpScripts"
    "instance-reset" = "Addmod_instance_resetScripts"
    "leech" = "Addmod_leechScripts"
    "low-level-rbg" = "Addmod_low_level_rbgScripts"
    "mod-account-mount" = "Addmod_account_mountsScripts"
    "mod-achievements" = "Addmod_account_achievementsScripts"
    "mod-ahbot" = "Addmod_ah_botScripts"
    "mod-aq-war-effort" = "Addmod_war_effortScripts"
    "mod-customserver" = "AddCustomServerScripts"
    "mod-learnspells" = "Addmod_learn_spellsScripts"
    "mod-moneyforkills" = "Addmod_money_for_killsScripts"
    "mod-pvptitles" = "Addmod_pvp_titlesScripts"
    "mod-reward-system" = "Addmod_reward_played_timeScripts"
    "morphsummon" = "Addmod_morphsummonScripts"
    "npc-spectator" = "Addmod_npc_spectatorScripts"
    "npc-subclass" = "Addmod_npc_subclassScripts"
    "npc-talent-template" = "Addmod_npc_talent_templateScripts"
    "skip-dk-module" = "Addmod_skip_dk_starting_areaScripts"
    "transmog" = "Addmod_transmogScripts"
    "who-logged" = "Addmod_who_loggedScripts"
}

$loaderCompatibilityWarnings = @()
foreach ($moduleDir in Get-ChildItem -Path (Join-Path $sourceRoot 'modules') -Directory -ErrorAction SilentlyContinue) {
    $warning = Sync-LoaderCompatibilityWrapper -ModuleRoot $moduleDir.FullName -LoaderSymbolOverrides $loaderSymbolOverrides
    if ($warning) {
        $loaderCompatibilityWarnings += $warning
    }
}

if ($loaderCompatibilityWarnings.Count -gt 0) {
    foreach ($warning in $loaderCompatibilityWarnings) {
        Write-Warning "Loader compatibility wrapper could not be generated for $($warning.module). expected=$($warning.expected) actual=$($warning.actual)"
    }
}

Write-Host "compatibility_overlay_applied=true workspace=$WorkspaceRoot"
